services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - ollama-network
    volumes:
      - ollama-data:/root/.ollama

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "8181:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    networks:
      - ollama-network
    volumes:
      - open-webui-data:/app/backend/data

networks:
  ollama-network:
    driver: bridge

volumes:
  ollama-data:
  open-webui-data:
