services:

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "8181:8080"
    environment:
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
    volumes:
      - open-webui-data:/app/backend/data
    networks:
      - default
    depends_on:
      - plugin-api


  plugin-api:
    build:
      context: ./SemanticKernelPlugins
      dockerfile: Dockerfile
    container_name: plugin-api
    environment:
      LMStudioUrl: ${LMStudioUrl}
    ports:
      - "11434:11434"
    networks:
      - default
    depends_on:
      - service-db


  service-db:
    container_name: service-db
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  open-webui-data:

networks:
  default:
    driver: bridge