services:
#  ollama:
#    image: ollama/ollama
#    container_name: ollama
#    ports:
#      - "11434:11434"
#    networks:
#      - ollama-network
#    volumes:
#      - ollama-data:/root/.ollama

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "8181:8080"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - open-webui-data:/app/backend/data

volumes:
  # ollama-data:
  open-webui-data:
